export default defineEventHandler(() => {
  return {
    Home: [
      {
        title: "Vue 3.5 Announced with Performance Boost",
        source: "https://tomaszs2.medium.com",
        tag: "Sponsored",
        timestamp: "1h ago",
        image: "/images/vue3.jpg",
      },
      {
        title: "Remote Work Trends for 2025",
        source: "remoteworkweekly.com",
        timestamp: "3h ago",
        image: "/images/vue3.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/minimalism.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/sinners.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/minimalism.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/sinners.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/minimalism.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/sinners.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/minimalism.jpg",
      },
      {
        title: "How Solar Energy is Shaping the Future",
        source: "greentech.org",
        tag: "Environment",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
    ],
    News: [
      {
        title: "2025 Midterm Elections Preview",
        source: "dailyreport.com",
        timestamp: "2h ago",
        image: "/images/2025midterm.jpg",
      },
      {
        title: "Climate Changes Impacting Global Crops",
        source: "climatebeat.org",
        tag: "Climate",
        timestamp: "4h ago",
        image: "/images/climate.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai2.jpg",
      },
      {
        title: "Climate Changes Impacting Global Crops",
        source: "climatebeat.org",
        tag: "Climate",
        timestamp: "4h ago",
        image: "/images/climate.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai2.jpg",
      },

      {
        title: "Climate Changes Impacting Global Crops",
        source: "climatebeat.org",
        tag: "Climate",
        timestamp: "4h ago",
        image: "/images/climate.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai2.jpg",
      },

      {
        title: "Climate Changes Impacting Global Crops",
        source: "climatebeat.org",
        tag: "Climate",
        timestamp: "4h ago",
        image: "/images/climate.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Breakthrough in AI-Powered Healthcare",
        source: "healthtechnews.com",
        tag: "Health",
        timestamp: "5h ago",
        image: "/images/ai2.jpg",
      },
    ],
    Sports: [
      {
        title: "Champions League Final Set for June 2025",
        source: "sportshub.com",
        timestamp: "30m ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
    ],
    Money: [
      {
        title: "Stock Market Rally Expected to Continue",
        source: "financenews.com",
        timestamp: "1h ago",
        image: "/images/stocks.jpg",
      },
      {
        title: "Cryptocurrency Regulations Tighten Worldwide",
        source: "cryptoinsights.org",
        tag: "Crypto",
        timestamp: "3h ago",
        image: "/images/stocks.jpg",
      },
      {
        title: "Tips for Saving More on Your Taxes",
        source: "moneymatters.com",
        timestamp: "5h ago",
        image: "/images/stocks.jpg",
      },

      {
        title: "Cryptocurrency Regulations Tighten Worldwide",
        source: "cryptoinsights.org",
        tag: "Crypto",
        timestamp: "3h ago",
        image: "/images/stocks.jpg",
      },
      {
        title: "Tips for Saving More on Your Taxes",
        source: "moneymatters.com",
        timestamp: "5h ago",
        image: "/images/stocks.jpg",
      },

      {
        title: "Cryptocurrency Regulations Tighten Worldwide",
        source: "cryptoinsights.org",
        tag: "Crypto",
        timestamp: "3h ago",
        image: "/images/stocks.jpg",
      },
      {
        title: "Tips for Saving More on Your Taxes",
        source: "moneymatters.com",
        timestamp: "5h ago",
        image: "/images/stocks.jpg",
      },
    ],
    Lifestyle: [
      {
        title: "Minimalism: The Art of Living With Less",
        source: "lifestyletoday.com",
        tag: "Wellness",
        timestamp: "2h ago",
        image: "/images/minimalism.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },

      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },

      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
    ],
    Politics: [
      {
        title: "New Policies Aim to Improve Urban Infrastructure",
        source: "policywatch.com",
        timestamp: "1h ago",
        image: "/images/politics.jpg",
      },
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },

      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
      ,
      {
        title: "Top 10 NBA Draft Picks This Season",
        source: "hoopsdaily.net",
        timestamp: "2h ago",
        image: "/images/champions.jpg",
      },
      {
        title: "Marathon Training Tips for Beginners",
        source: "runfastmag.com",
        tag: "Fitness",
        timestamp: "4h ago",
        image: "/images/champions.jpg",
      },
    ],
    Health: [
      {
        title: "New Research on the Benefits of Meditation",
        source: "wellnessdaily.com",
        tag: "Mindfulness",
        timestamp: "2h ago",
        image: "/images/meditation.jpg",
      },
      {
        title: "The Rise of Telehealth Services in 2025",
        source: "healthtechnews.com",
        timestamp: "4h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Superfoods to Boost Your Immune System",
        source: "nutritiontoday.org",
        timestamp: "6h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Superfoods to Boost Your Immune System",
        source: "nutritiontoday.org",
        timestamp: "6h ago",
        image: "/images/ai.jpg",
      },
      {
        title: "Superfoods to Boost Your Immune System",
        source: "nutritiontoday.org",
        timestamp: "6h ago",
        image: "https://source.unsplash.com/featured/?superfoods",
      },
      {
        title: "Superfoods to Boost Your Immune System",
        source: "nutritiontoday.org",
        timestamp: "6h ago",
        image: "https://source.unsplash.com/featured/?superfoods",
      },
      {
        title: "Superfoods to Boost Your Immune System",
        source: "nutritiontoday.org",
        timestamp: "6h ago",
        image: "https://source.unsplash.com/featured/?superfoods",
      },
    ],
    Food: [
      {
        title: "Exploring Exotic Flavors: A Culinary Journey",
        source: "foodlover.com",
        timestamp: "1h ago",
        image: "/images/food.jpg",
      },
      {
        title: "The Best Summer Cocktails to Try This Year",
        source: "mixologyworld.net",
        tag: "Drinks",
        timestamp: "3h ago",
        image: "/images/ai2.jpg",
      },
      {
        title: "Plant-Based Diets: Benefits and Recipes",
        source: "healthyeats.org",
        timestamp: "5h ago",
        image: "/images/ai2.jpg",
      },
      {
        title: "Plant-Based Diets: Benefits and Recipes",
        source: "healthyeats.org",
        timestamp: "5h ago",
        image: "https://source.unsplash.com/featured/?plantbased",
      },
      {
        title: "Plant-Based Diets: Benefits and Recipes",
        source: "healthyeats.org",
        timestamp: "5h ago",
        image: "https://source.unsplash.com/featured/?plantbased",
      },
      {
        title: "Plant-Based Diets: Benefits and Recipes",
        source: "healthyeats.org",
        timestamp: "5h ago",
        image: "https://source.unsplash.com/featured/?plantbased",
      },
      {
        title: "Plant-Based Diets: Benefits and Recipes",
        source: "healthyeats.org",
        timestamp: "5h ago",
        image: "https://source.unsplash.com/featured/?plantbased",
      },
    ],
    Entertainment: [
      {
        title: "Top Box Office Hits of 2025",
        source: "moviebuzz.com",
        timestamp: "2h ago",
        image: "/images/sinners.jpg",
      },
      {
        title: "Interview with Award-Winning Director",
        source: "cinephilemag.net",
        timestamp: "4h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "Music Festivals to Watch This Summer",
        source: "festivalseason.com",
        tag: "Music",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "Music Festivals to Watch This Summer",
        source: "festivalseason.com",
        tag: "Music",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "Music Festivals to Watch This Summer",
        source: "festivalseason.com",
        tag: "Music",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "Music Festivals to Watch This Summer",
        source: "festivalseason.com",
        tag: "Music",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
      {
        title: "Music Festivals to Watch This Summer",
        source: "festivalseason.com",
        tag: "Music",
        timestamp: "6h ago",
        image: "/images/greentech.jpg",
      },
    ],
  };
});
